### ISSUE TITLE
afra with no options just hangs

### ISSUE THREAD

**Issue by tseemann** [EvolBioInf/afra#2]
Is it waiting for `stdin` ?

**Comment by kloetzl** [comment]
yeah, just like any other unix program, basically (head, cat, …).

**Comment by tseemann** [comment]
FYI - i think it is possible to check if `stdin` is a pipe or a TTY and produce `-h` if there is no `stdin`, if you are keen!

It could print to `stderr` saying `Reading from stdin...` maybe.

**Comment by tseemann** [comment]
Thank you.

**Comment by kloetzl** [comment]
I still have to work on the wording, but I'll probably adopt similar mechanics for my other tools.
